version: '3.9'
services:
  alurabooks:
    image: aluradocker/alura-books:1.0
    container_name: alurabooks
    networks: 
      - compose-bridge
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:4.4.6
    container_name: meu-mongo
    networks: 
      - compose-bridge

networks:
  compose-bridge:
    driver: bridge